"""add_privacy_fields_to_album_v2

Revision ID: 32aadf56da7b
Revises: 4706fdd46555
Create Date: 2026-03-18 01:28:36.856114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32aadf56da7b'
down_revision = '4706fdd46555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_publico', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('proyecto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'proyectos', ['proyecto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albumes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proyecto_id')
        batch_op.drop_column('es_publico')

    # ### end Alembic commands ###
