"""Add Columna model and link to Tarea

Revision ID: 3ad65cdb2556
Revises: e2f6700168ec
Create Date: 2026-03-18 17:20:28.350048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ad65cdb2556'
down_revision = 'e2f6700168ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('columnas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('columna_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'columnas', ['columna_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('columna_id')

    op.drop_table('columnas')
    # ### end Alembic commands ###
