"""Agregar vinculacion Proyecto y Equipo

Revision ID: 4706fdd46555
Revises: a4c047d2ebe7
Create Date: 2026-03-15 03:14:01.128764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4706fdd46555'
down_revision = 'a4c047d2ebe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'equipos', ['equipo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('equipo_id')

    # ### end Alembic commands ###
