"""Add Tarea model for Kanban system

Revision ID: 9d74b124a2ef
Revises: 32aadf56da7b
Create Date: 2026-03-18 04:47:11.483912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d74b124a2ef'
down_revision = '32aadf56da7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('prioridad', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('asignado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tareas')
    # ### end Alembic commands ###
