"""Remove state column from Tarea

Revision ID: 9e44826acfe6
Revises: 3ad65cdb2556
Create Date: 2026-03-18 17:23:42.103995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e44826acfe6'
down_revision = '3ad65cdb2556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.alter_column('columna_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('columna_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
