"""Agregar modelo Equipo y vinculacion con User

Revision ID: a4c047d2ebe7
Revises: 3b1b44388d70
Create Date: 2026-03-15 02:36:49.038191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4c047d2ebe7'
down_revision = '3b1b44388d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.create_foreign_key(None, 'equipos', ['equipo_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('equipo_id')
        batch_op.drop_column('user_id')

    op.drop_table('equipos')
    # ### end Alembic commands ###
