"""Add etiquetas to Tarea

Revision ID: caa026cea075
Revises: 9e44826acfe6
Create Date: 2026-03-19 10:23:06.257732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa026cea075'
down_revision = '9e44826acfe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('etiquetas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_column('etiquetas')

    # ### end Alembic commands ###
